name: Build and deploy takelslim

on:
  schedule: # run daily at midnight CET
    - cron:  '0 1 * * *'
  workflow_dispatch: # allow manual trigger

jobs:
  build-and-deploy-takelbase:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: 2.7

      - name: Install tau
        run: gem install takelage

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass --no-gpg --no-ssh" >> $HOME/.takelage.yml
          cat $HOME/.takelage.yml

      - name: Pull takelage image
        run: tau update

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Lint ruby
        run: tau docker container command "rake rubylint"

      - name: Build takelage takelbase image with packer
        run: tau docker container command "rake image:docker:takelslim:base:debian10"

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push image
        run: |
          tau docker container command "rake dockerhub:takelslim:base:registry:tag"
          tau docker container command "rake dockerhub:takelslim:base:registry:push"
